/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdlib.h>
#include <stdio.h>
#include <android/log.h>
/* Header for class com_testjni_test_Student */

#ifndef _Included_com_testjni_test_Student
#define _Included_com_testjni_test_Student

// log标签
#define  TAG    "这里填写日志的TAG"
// 定义info信息
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,TAG,__VA_ARGS__)
// 定义debug信息
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, TAG, __VA_ARGS__)
// 定义error信息
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR,TAG,__VA_ARGS__)
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_testjni_test_Student
 * Method:    setJniString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_com_testjni_test_Student_setJniString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_testjni_test_Student
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_testjni_test_Student_getJniString
  (JNIEnv *, jobject);

/*
 * Class:     com_testjni_test_Student
 * Method:    addNum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_testjni_test_Student_addNum
  (JNIEnv *, jobject, jint, jint);

JNIEXPORT jint JNICALL Java_com_testjni_test_Student_sumArray
  (JNIEnv *, jobject, jintArray);

JNIEXPORT jobjectArray JNICALL Java_com_testjni_test_Student_getJniStringArray
  (JNIEnv *, jobject);

JNIEXPORT jobject JNICALL Java_com_testjni_test_Student_getJniStudentObj
  (JNIEnv *, jobject);

JNIEXPORT jintArray JNICALL Java_com_testjni_test_Student_ChangeImgToGray
  (JNIEnv *, jobject, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
